spring:
    application:
        name: passenger-core
    datasource:
        url: jdbc:mysql://localhost/passengerJos?useUnicode=yes&characterEncoding=UTF-8&autoReconnect=true&useCompression=true&useSSL=false&allowPublicKeyRetrieval=true&nullNamePatternMatchesAll=true
        username: jos
        password: jos
        driver-class-name: com.mysql.cj.jdbc.Driver
    liquibase:
        change-log: classpath:database/changelog/db.changelog-master.xml
        database-change-log-table: pax_data_change_log
        database-change-log-lock-table: pax_data_change_log_lock
    activemq:
        packages:
            trust-all: true

logging:
    config: classpath:logging/log4j2.xml      

passenger:
    update:
        jms:
            source: jms:queue:passenger.update
